### ISSUE TITLE
PageSuck Gray Screen of Death?

### ISSUE THREAD

**Issue by tonyellard** [timburgess/brackets-pagesuck#1]
Working on Windows 8, Brackets sprint 27.

When I first chose a site to suck I was getting an error about the directory. this was resolved by running brackets as administrator.

Now after I suck a page I it appears brackets gets the content but everything is grayed out and I cannot work with anything.

**Comment by timburgess** [comment]
Yes, I think I know what this is. At some point Brackets has moved to a new version of Twitter Bootstrap and the modal background is not being dismissed anymore. So the dialog box disappears and yet the editor is still unreachable. Am fixing this and also other changes so that PageSuck works with new Extensions registry in Sprint 28. Will announce on brackets-dev group when changes made.

**Comment by timburgess** [comment]
I have pushed up new code that fixes this and PageSuck will now display the retrieved html correctly. I have tested this on Mac and Linux. Would be great if you can confirm that it works on Windows too.

**Comment by tonyellard** [comment]
Tested just now on Windows 7 with Sprint 28 and it looks good. The modal closes correctly.

**Comment by timburgess** [comment]
Thanks Tony. I'll close this issue then.
